export interface Player {
  id: string
  name: string
  role: string
  battingStyle: string
  bowlingStyle: string
  nationality: string
  age: number
  matches: number
  runs: number
  wickets: number
  average: number
  strikeRate: number
  economy?: number
  image: string
  bio: string
  achievements: string[]
  seasons: string[]
  isLegend: boolean
}

export const playersData: Player[] = [
  {
    id: "ms-dhoni",
    name: "MS Dhoni",
    role: "Wicket-keeper Batsman",
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    nationality: "India",
    age: 42,
    matches: 264,
    runs: 5082,
    wickets: 0,
    average: 39.1,
    strikeRate: 135.9,
    image: "/ms-dhoni-csk-captain-cricket.jpg",
    bio: "The legendary Captain Cool who led CSK to 5 IPL titles. Known for his finishing abilities and tactical brilliance.",
    achievements: [
      "5x IPL Champion",
      "3x IPL Final Man of the Match",
      "Most successful IPL captain",
      "Highest runs as wicket-keeper in IPL",
    ],
    seasons: ["2008-2015", "2018-2023"],
    isLegend: true,
  },
  {
    id: "suresh-raina",
    name: "Suresh Raina",
    role: "Batsman",
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm off-break",
    nationality: "India",
    age: 37,
    matches: 205,
    runs: 5528,
    wickets: 25,
    average: 32.5,
    strikeRate: 136.7,
    image: "/suresh-raina-csk-batsman-cricket.jpg",
    bio: "Mr. IPL and CSK's highest run-scorer. The backbone of CSK's batting lineup for over a decade.",
    achievements: ["Highest run-scorer for CSK", "Most catches in IPL", "4x IPL Champion", "IPL Orange Cap winner"],
    seasons: ["2008-2015", "2018-2021"],
    isLegend: true,
  },
  {
    id: "ravindra-jadeja",
    name: "Ravindra Jadeja",
    role: "All-rounder",
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    nationality: "India",
    age: 35,
    matches: 240,
    runs: 2756,
    wickets: 157,
    average: 24.8,
    strikeRate: 127.3,
    economy: 7.68,
    image: "/ravi.jpeg",
    bio: "Sir Jadeja - the ultimate all-rounder with exceptional fielding skills. A key player in CSK's success.",
    achievements: [
      "Most wickets for CSK",
      "Best fielder in IPL",
      "4x IPL Champion",
      "Multiple Man of the Match awards",
    ],
    seasons: ["2012-2015", "2018-2024"],
    isLegend: true,
  },
  {
    id: "dwayne-bravo",
    name: "Dwayne Bravo",
    role: "All-rounder",
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium-fast",
    nationality: "West Indies",
    age: 40,
    matches: 161,
    runs: 1560,
    wickets: 183,
    average: 23.1,
    strikeRate: 130.2,
    economy: 8.38,
    image: "/dwayne-bravo-csk-all-rounder-cricket.jpg",
    bio: "DJ Bravo - the death bowling specialist and entertainer. Known for his variations and celebrations.",
    achievements: ["Purple Cap winner", "Most wickets in IPL history", "3x IPL Champion", "Best death bowler"],
    seasons: ["2011", "2015", "2018-2022"],
    isLegend: true,
  },
   {
    id: "murali-vijay",
    name: "Murali Vijay",
    role: "Batsman",
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    nationality: "India",
    age: 41,
    matches: 106,
    runs: 2587,
    wickets: 0,
    average: 28.0,
    strikeRate: 126.2,
    image: "/murali-vijay-csk-batsman-cricket.jpg",
    bio: "Stylish opener, Vijay played several memorable knocks for CSK in playoffs and finals.",
    achievements: [
      "2x IPL Champion",
      "Best individual score for CSK in playoffs",
      "Consistent performer in big matches"
    ],
    seasons: ["2009-2013", "2018-2020"],
    isLegend: true,
  },
  {
    id: "ambati-rayudu",
    name: "Ambati Rayudu",
    role: "Batsman",
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    nationality: "India",
    age: 39,
    matches: 104,
    runs: 2200,
    wickets: 0,
    average: 29.7,
    strikeRate: 128.5,
    image: "/ambati-rayudu-csk-batsman-cricket.jpg",
    bio: "A reliable middle-order batsman, Rayudu played several match-winning knocks for CSK.",
    achievements: [
      "3x IPL Champion",
      "Key player in 2018 title win",
      "Consistent performer in playoffs"
    ],
    seasons: ["2018-2023"],
    isLegend: true,
  },
   {
    id: "michael-hussey",
    name: "Michael Hussey",
    role: "Batsman",
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm medium",
    nationality: "Australia",
    age: 49,
    matches: 50,
    runs: 1768,
    wickets: 0,
    average: 42.1,
    strikeRate: 123.6,
    image: "/michael-hussey-csk-batsman-cricket.jpg",
    bio: "Mr. Cricket was CSK's reliable opener, known for his consistency and calmness under pressure.",
    achievements: [
      "IPL Orange Cap winner 2013",
      "2x IPL Champion",
      "CSK's highest run-scorer in 2013"
    ],
    seasons: ["2008-2013", "2015"],
    isLegend: true,
  },
  {
    id: "shane-watson",
    name: "Shane Watson",
    role: "All-rounder",
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium-fast",
    nationality: "Australia",
    age: 44,
    matches: 43,
    runs: 1252,
    wickets: 19,
    average: 33.8,
    strikeRate: 137.9,
    economy: 8.2,
    image: "/shane-watson-csk-all-rounder-cricket.jpg",
    bio: "Australian all-rounder who played match-winning knocks in IPL finals. Known for his power hitting and big-match temperament.",
    achievements: [
      "2x IPL Champion",
      "Man of the Match in 2018 IPL Final",
      "Centurion in IPL 2018 Final"
    ],
    seasons: ["2018-2020"],
    isLegend: true,
  },
  {
    id: "albie-morkel",
    name: "Albie Morkel",
    role: "All-rounder",
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm medium-fast",
    nationality: "South Africa",
    age: 43,
    matches: 91,
    runs: 827,
    wickets: 76,
    average: 24.3,
    strikeRate: 142.3,
    economy: 8.1,
    image: "/albie-morkel-csk-all-rounder-cricket.jpg",
    bio: "Powerful all-rounder, Morkel was famous for his big sixes and crucial breakthroughs.",
    achievements: [
      "2x IPL Champion",
      "Iconic sixes in 2012 chase",
      "Key all-rounder in CSK's early years"
    ],
    seasons: ["2008-2013"],
    isLegend: true,
  },
  {
    id: "ruturaj-gaikwad",
    name: "Ruturaj Gaikwad",
    role: "Batsman",
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm off-break",
    nationality: "India",
    age: 27,
    matches: 67,
    runs: 2380,
    wickets: 0,
    average: 37.8,
    strikeRate: 134.9,
    image: "/ruturaj-gaikwad-csk-batsman-cricket.jpg",
    bio: "The young sensation and current CSK captain. Known for his elegant stroke play and consistency.",
    achievements: [
      "Orange Cap winner 2021",
      "Emerging Player Award",
      "1x IPL Champion",
      "Fastest to 2000 runs for CSK",
    ],
    seasons: ["2020-2024"],
    isLegend: false,
  },
  {
    id: "ms-dhoni",
    name: "MS Dhoni",
    role: "Wicket-keeper Batsman",
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm medium",
    nationality: "India",
    age: 42,
    matches: 264,
    runs: 5082,
    wickets: 0,
    average: 39.1,
    strikeRate: 135.9,
    image: "/ms-dhoni-csk-captain-cricket-current.jpg",
    bio: "The legendary Captain Cool who led CSK to 5 IPL titles. Known for his finishing abilities and tactical brilliance.",
    achievements: [
      "5x IPL Champion",
      "3x IPL Final Man of the Match",
      "Most successful IPL captain",
      "Highest runs as wicket-keeper in IPL",
    ],
    seasons: ["2008-2015", "2018-2023"],
    isLegend: false,
  },
  {
    id: "ravindra-jadeja",
    name: "Ravindra Jadeja",
    role: "All-rounder",
    battingStyle: "Left-handed",
    bowlingStyle: "Left-arm orthodox",
    nationality: "India",
    age: 35,
    matches: 240,
    runs: 2756,
    wickets: 157,
    average: 24.8,
    strikeRate: 127.3,
    economy: 7.68,
    image: "/ravi-csk-all-rounder-cricket.jpg",
    bio: "Sir Jadeja - the ultimate all-rounder with exceptional fielding skills. A key player in CSK's success.",
    achievements: [
      "Most wickets for CSK",
      "Best fielder in IPL",
      "4x IPL Champion",
      "Multiple Man of the Match awards",
    ],
    seasons: ["2012-2015", "2018-2024"],
    isLegend: false,
  },
  {
   id: "shivam-dube",
    name: "Shivam Dube",
    role: "All-rounder",
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm medium",
    nationality: "India",
    age: 31,
    matches: 45,
    runs: 1100,
    wickets: 12,
    average: 29.7,
    strikeRate: 145.3,
    image: "/shivam-dube-csk-all-rounder-cricket.jpg",
    bio: "Powerful middle-order hitter and handy bowler, Dube has become a match-winner for CSK.",
    achievements: [
      "Most sixes for CSK in 2023",
      "Key player in 2023 title run"
    ],
    seasons: ["2022-2025"],
    isLegend: false,
  },
  {  
  id: "dewald-brevis",
  name: "Dewald Brevis",
  role: "Batsman",
  battingStyle: "Right-handed",
  bowlingStyle: "Right-arm leg-break",
  nationality: "South Africa",
  age: 22,
  matches: 16,
  runs: 455,
  wickets: 1,
  average: 28.44,
  strikeRate: 153.20,
  image: "/brewis-csk-batsman-cricket.jpg", 
  bio: "Nicknamed 'Baby AB', Brevis is a young South African sensation known for his explosive batting and 360-degree play.",
  achievements: [
    "U19 World Cup star",
    "Fastest T20 century in SA domestic cricket"
  ],
  seasons: ["2025"],
  isLegend: false,
},
{
  id: "ayush-mhatre",
  name: "Ayush Mhatre",
  role: "Batsman",
  battingStyle: "Right-handed",
  bowlingStyle: "Right-arm off-break",
  nationality: "India",
  age: 23,
  matches: 7,
  runs: 240,
  wickets: 0,
  average: 34.29,
  strikeRate: 188.98,
  image: "/ayush-mhatre-csk-batsman-cricket.jpg", 
  bio: "Young Indian batsman known for his solid technique and promising performances in domestic cricket.",
  achievements: [
    "Impressive domestic debut",
    "Emerging talent in 2025 squad"
  ],
  seasons: ["2025"],
  isLegend: false,
},

  {
    id: "matheesha-pathirana",
    name: "Matheesha Pathirana",
    role: "Bowler",
    battingStyle: "Right-handed",
    bowlingStyle: "Right-arm fast",
    nationality: "Sri Lanka",
    age: 22,
    matches: 32,
    runs: 0,
    wickets: 47,
    average: 0,
    strikeRate: 0,
    economy: 8.68,
    image: "/matheesha-pathirana-csk-bowler-cricket.jpg",
    bio: "The 'Baby Malinga' with a slingy action, Pathirana is CSK's death-overs specialist.",
    achievements: [
      "Best young bowler 2023",
      "Key death bowler for CSK"
    ],
    seasons: ["2022-2025"],
    isLegend: false,
  },
  {
  id: "anshul-khamboj",
  name: "Anshul Khamboj",
  role: "Batsman",
  battingStyle: "Right-handed",
  bowlingStyle: "Right-arm off-break",
  nationality: "India",
  age: 22,
  matches: 3,
  runs: 54,
  wickets: 0,
  average: 18.0,
  strikeRate: 125.0,
  image: "/anshul-khamboj-csk-batsman-cricket.jpg", 
  bio: "Young Indian batsman, Anshul Khamboj is known for his aggressive intent and promising domestic performances.",
  achievements: [
    "Emerging player in 2025 squad",
    "Notable domestic T20 performances"
  ],
  seasons: ["2025"],
  isLegend: false,
},
  {
  id: "noor-ahmad",
  name: "Noor Ahmad",
  role: "Bowler",
  battingStyle: "Left-handed",
  bowlingStyle: "Left-arm wrist spin",
  nationality: "Afghanistan",
  age: 20,
  matches: 25,
  runs: 40,
  wickets: 28,
  average: 22.4,
  strikeRate: 7.5,
  economy: 7.7,
  image: "/noor-ahmad-csk-bowler-cricket.jpg",
  bio: "Young Afghan wrist-spinner, Noor Ahmad is known for his variations and wicket-taking ability.",
  achievements: [
    "Impressive IPL debut season",
    "Afghanistan T20I regular"
  ],
  seasons: ["2025"],
  isLegend: false,
},
{
  id: "sam-curran",
  name: "Sam Curran",
  role: "All-rounder",
  battingStyle: "Left-handed",
  bowlingStyle: "Left-arm medium-fast",
  nationality: "England",
  age: 26,
  matches: 32,
  runs: 382,
  wickets: 32,
  average: 23.9,
  strikeRate: 143.8,
  economy: 8.5,
  image: "/sam-curran-csk-all-rounder-cricket.jpg", // Update if your filename is different
  bio: "Dynamic English all-rounder, Sam Curran impressed with both bat and ball during his CSK stint, especially in the powerplay and death overs.",
  achievements: [
    "Hat-trick for CSK in 2020",
    "Key all-rounder in 2020 and 2021 seasons",
    "England T20 World Cup winner"
  ],
  seasons: ["2020-2021", "2025"],
  isLegend: false,
},

  {
    id: "devon-conway",
    name: "Devon Conway",
    role: "Batsman",
    battingStyle: "Left-handed",
    bowlingStyle: "Right-arm medium",
    nationality: "New Zealand",
    age: 34,
    matches: 30,
    runs: 1100,
    wickets: 0,
    average: 42.3,
    strikeRate: 137.5,
    image: "/devon-conway-csk-batsman-cricket.jpg",
    bio: "New Zealand opener, Conway is known for his consistency and big-match temperament.",
    achievements: [
      "CSK's top scorer in 2023 final"
    ],
    seasons: ["2022-2025"],
    isLegend: false,
  },
  {
  id: "rachin-ravindra",
  name: "Rachin Ravindra",
  role: "All-rounder",
  battingStyle: "Left-handed",
  bowlingStyle: "Left-arm orthodox",
  nationality: "New Zealand",
  age: 25,
  matches: 10,
  runs: 220,
  wickets: 7,
  average: 27.5,
  strikeRate: 134.0,
  economy: 7.5,
  image: "/rachin-ravindra-csk-all-rounder-cricket.jpg",
  bio: "Talented New Zealand all-rounder, known for his aggressive batting and handy spin bowling.",
  achievements: [
    "Breakout star at 2023 World Cup",
    "CSK debut 2025"
  ],
  seasons: ["2025"],
  isLegend: false,
},
{
  id: "urvil-patel",
  name: "Urvil Patel",
  role: "Wicket-keeper Batsman",
  battingStyle: "Right-handed",
  bowlingStyle: "Right-arm off-break",
  nationality: "India",
  age: 25,
  matches: 6,
  runs: 112,
  wickets: 0,
  average: 22.4,
  strikeRate: 135.0,
  image: "/urvil-patel-csk-wicketkeeper-cricket.jpg", // Update if your filename is different
  bio: "Young wicket-keeper batsman, Urvil Patel is known for his aggressive batting and sharp glovework.",
  achievements: [
    "Impressive domestic T20 performances",
    "Emerging player in 2025 squad"
  ],
  seasons: ["2025"],
  isLegend: false,
},
{
  id: "mukesh-choudhary",
  name: "Mukesh Choudhary",
  role: "Bowler",
  battingStyle: "Left-handed",
  bowlingStyle: "Left-arm medium-fast",
  nationality: "India",
  age: 28,
  matches: 17,
  runs: 18,
  wickets: 20,
  average: 26.9,
  strikeRate: 8.5,
  economy: 8.5,
  image: "/Mukesh-csk-bowler-cricket.jpg", // Update if your filename is different
  bio: "Left-arm pacer, Mukesh Choudhary impressed with his swing and wicket-taking ability in the powerplay.",
  achievements: [
    "CSK's leading powerplay wicket-taker 2022",
    "Consistent performer in domestic cricket"
  ],
  seasons: ["2022", "2025"],
  isLegend: false,
},
{
  id: "shaikh-rasheed",
  name: "Shaikh Rasheed",
  role: "Batsman",
  battingStyle: "Right-handed",
  bowlingStyle: "Right-arm off-break",
  nationality: "India",
  age: 20,
  matches: 2,
  runs: 28,
  wickets: 0,
  average: 14.0,
  strikeRate: 120.0,
  image: "/shaikh-rasheed-csk-batsman-cricket.jpg", // Update if your filename is different
  bio: "Young Indian batsman, Shaikh Rasheed is known for his solid technique and performances in U19 cricket.",
  achievements: [
    "India U19 World Cup finalist",
    "Emerging talent in 2025 squad"
  ],
  seasons: ["2025"],
  isLegend: false,
},
{
  id: "deepak-hooda",
  name: "Deepak Hooda",
  role: "All-rounder",
  battingStyle: "Right-handed",
  bowlingStyle: "Right-arm off-break",
  nationality: "India",
  age: 29,
  matches: 100,
  runs: 1230,
  wickets: 18,
  average: 22.8,
  strikeRate: 132.5,
  economy: 7.9,
  image: "/deepak-hooda-csk-all-rounder-cricket.jpg",
  bio: "Dynamic Indian all-rounder, Hooda is known for his power-hitting and useful off-spin.",
  achievements: [
    "Consistent IPL performer",
    "India T20I debutant"
  ],
  seasons: ["2025"],
  isLegend: false,
},
{
  id: "rahul-tripathi",
  name: "Rahul Tripathi",
  role: "Batsman",
  battingStyle: "Right-handed",
  bowlingStyle: "Right-arm medium",
  nationality: "India",
  age: 33,
  matches: 89,
  runs: 1900,
  wickets: 0,
  average: 27.1,
  strikeRate: 140.2,
  image: "/rahul-tripathi-csk-batsman-cricket.jpg",
  bio: "Aggressive top-order batsman, Tripathi is known for his fearless approach and quick scoring.",
  achievements: [
    "Key knocks for multiple IPL teams",
    "India T20I debutant"
  ],
  seasons: ["2025"],
  isLegend: false,
},
{
  id: "vijay-shankar",
  name: "Vijay Shankar",
  role: "All-rounder",
  battingStyle: "Right-handed",
  bowlingStyle: "Right-arm medium",
  nationality: "India",
  age: 34,
  matches: 70,
  runs: 1010,
  wickets: 12,
  average: 23.5,
  strikeRate: 128.0,
  economy: 8.1,
  image: "/vijay-shankar-csk-all-rounder-cricket.jpg",
  bio: "Versatile all-rounder, Shankar is known for his calm batting and useful medium pace.",
  achievements: [
    "India World Cup squad 2019",
    "Multiple match-winning IPL knocks"
  ],
  seasons: ["2025"],
  isLegend: false,
},
  
  
]

export function getPlayerById(id: string): Player | undefined {
  return playersData.find((player) => player.id === id)
}

export function getPlayersByRole(role: string): Player[] {
  return playersData.filter((player) => player.role.toLowerCase().includes(role.toLowerCase()))
}

export function getLegendaryPlayers(): Player[] {
  return playersData.filter((player) => player.isLegend)
}
